const mongoose=require("mongoose")

const orderSchema=mongoose.Schema(
    {
    shippingInfo:{
        address:{
            type:String,
            required:true
        },
        city:{
            type:String,
            required:true
        },
        state:{
            type:String,
            required:true
        },
        Pincode:{
            type:Number,
            required:true
        }
        

    },
    user:{
        type:mongoose.Schema.ObjectId,
        ref:"User",
        required:true        

    },
    orderItems:[{
        productname:{
            type:String,
            required:true
        },
        quantity:{
            type:Number,
            required:true
        },
        price:{
            type:Number,
            required:true
        },
        image:{
            type:String,
            required:true
        },
        product:{
            type:mongoose.Schema.ObjectId,
            ref:"Product",
            required:true
        }

    }],
    paidAt:{
           type:Date,
           required:true
    },
    paymentInfo:{
        id:{
            type:Number,
            required:true
        },
        status:{
            type:String,
            required:true
        }
    },
    itemPrices:{
         type:Number,
         default:0,
         required:true
    },
    taxPrice:{
        type:Number,
        default:0,
        required:true
    },
    shippingPrice:{
        type:Number,
        default:0,
        required:true
    },
    totalPrice:{
            type:Number,
            default:0,
            required:true

    },
orderStatus:{
    type:String,
    required:true,
    default:"Processing",

},
deliveredAt:{
    type:Date
},
createdAt:{
    type:Date,
    required:true,
    default:Date.now()
},
}
)
module.exports=mongoose.model("orderModel",orderSchema)